#/bin/bash
#Wes Dillingham
#wes_dillingham@harvard.edu
#Research Computing - Harvard University 
#All Rights Reserved

###### DO NOT Modify this script outside of the puppet repo, it is a template generated by puppet.
###### Any modifications directly to this file will be overwritten @ the next Puppet Run
#For every Ceph cluster, a group of scripts is to be deployed, including this one, it is dynamically populated by 
#Puppet, as a template, and is specific only to the cluster it is generated for, this is not a general pupose 
#script for use with ANY given ceph cluster, it is only to be used with this cluster.


#PURPOSE:
#This script is used to describe the members of a Ceph cluster, Specifically: 






#Output the name of this cluster:

#Output the Metadata Servers of this cluster.

#Output the Monitors of this cluster.

#Output the OSDs of this cluster:

