#/bin/bash
#Wes Dillingham
#wes_dillingham@harvard.edu
#Research Computing - Harvard University 
#All Rights Reserved

###### DO NOT Modify this script outside of the puppet repo, it is a template generated by puppet.
###### Any modifications directly to this file will be overwritten @ the next Puppet Run
#For every Ceph cluster, a group of scripts is to be deployed, including this one, it is dynamically populated by 
#Puppet, as a template, and is specific only to the cluster it is generated for, this is not a general pupose 
#script for use with ANY given ceph cluster, it is only to be used with this cluster.


#PURPOSE:
#This script is used to configure virtual disks and wipe clean those disks of a to-be-deployed ceph cluster. Note this is  NEVER EVER EVER to be used on a running cluster. The Purpose of this script is to create and wipe disks, YOUR DATA WILL BE DESTROYED if you run this script




#omreport storage pdisk pdisk=0:0:1 controller=0
#omreport storage vdisk vdisk=0 controller=0
#omreport storage vdisk controller=0 | grep "/dev" | grep -v "/dev/sda"

echo "This script makes Virtual disks on target systems and destroys any data contained on those physical disks"
echo "This script attempts to preserve the root disk configuration - It does not interfere with the root disk or its corresponding virtual disks"
echo "Only run this script if you are positive you are okay with full data loss on the target systems"


echo "The Systems which will be acted upon are:"
######


#Determine Virtual Disk holding root image
#We assume that it is the first virtual disk of the first controller, if its not we end the script
#This is logical to assume as at this point it should be one virtual disk (2 physical disks) in a 
#RAID-1 Mirror
if [ `omreport storage vdisk controller=0 vdisk=0 | grep Layout | awk '{print $3}'` == "RAID-1" ]; then
	echo "Root disk found at: "
	omreport storage vdisk controller=0 vdisk=0 | grep -i "virtual disk"
	omreport storage vdisk controller=0 vdisk=0 | grep -i "Device Name"
	echo "Script will proceed with making RAID-0 VDs for remaining disks"
else
	echo "Root disk could not be safely determined or does not exist, the only safe thing to do for this script is to die"
fi	 


#Now we need to count the physical disks
NUMPHYSICALDISKS=`omreport storage pdisk controller=0 | grep -i Serial | wc -l`
echo "Number of Physical Disks is: $NUMPHYSICALDISKS"
#Disk identifiers start at 0, and go up so the first two disks (root disks) are 0:0:0 and 0:0:1
let "NUMDISKLABELS=$NUMPHYSICALDISKS - 1"

for DISKNUM in `seq 2 $NUMDISKLABELS`;
do
	SIZEOFPYSICALDISK=`omreport storage pdisk controller=0 pdisk=0:0:$DISKNUM | grep Capacity | awk '{print $3}'`
	echo "Now preparing a RAID-0 VD on the PD: 0:0:$DISKNUM with size of $SIZEOFPYSICALDISK GB"
done


